---
- name: Install yum-cron.
  sudo: yes
  yum:
    name: yum-cron
    state: present

- name: Copy the configuration file.
  sudo: yes
  template:
    src: etc/sysconfig/yum-cron.j2
    dest: /etc/sysconfig/yum-cron
  notify:
    - restart yum-cron

- name: Start yum-cron.
  sudo: yes
  service:
    name: yum-cron
    state: running
    enabled: yes